### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by vmrfriz** [dipeshsukhia/laravel-html-minify#10]
Please, update to Laravel 10, the extension is just great!

**Comment by projct1** [comment]
Agree!

**Comment by dipeshsukhia** [comment]
Dear User,

I hope you are doing well. I am writing to you as the maintainer of the Laravel-HTML-minify package on GitHub. I want to inform you about the current state of the project and kindly request financial assistance to support its ongoing maintenance and updates.

Laravel-HTML-minify is an open-source project that I have been developing and maintaining voluntarily. However, maintaining and updating the package requires a significant amount of time, effort, and resources.

I believe that continuing to enhance and improve Laravel-HTML-minify will greatly benefit the users and the wider community. With financial support, I will be able to dedicate more time to the project, ensuring timely updates, bug fixes, and the implementation of new features.

Your contribution will help cover expenses such as:

Bug fixing and feature implementation: With your support, I can prioritize addressing reported issues, fixing bugs, and implementing new features based on user feedback.

I have set up a funding campaign on GitHub to collect donations for Laravel-HTML-minify. The link to the campaign can be found here: **[Become a sponsor of Dipesh Sukhia](https://github.com/sponsors/dipeshsukhia)**

Any amount you can contribute would be greatly appreciated and will directly contribute to the project's sustainability and growth.

Your support will be vital in ensuring the continued development and maintenance of Laravel-HTML-minify.

Warm regards,
Dipesh Sukhia

**Comment by AnnoyingTechnology** [comment]
Any news on Laravel 10 support ?

**Comment by dipeshsukhia** [comment]
> Any news on Laravel 10 support ?
Please review comment. 
https://github.com/dipeshsukhia/laravel-html-minify/issues/10#issuecomment-1556524103

**Comment by AnnoyingTechnology** [comment]
> > Any news on Laravel 10 support ?
> > Please review comment.
> > [#10 (comment)](https://github.com/dipeshsukhia/laravel-html-minify/issues/10#issuecomment-1556524103)

Thanks for the answer, although it doesn't really answer the question. 
Are you explicitly asking for paid development to port to Laravel 10 ? If so, at what price ?

**Comment by dipeshsukhia** [comment]
> > > Any news on Laravel 10 support ?
> > > Please review comment.
> > > [#10 (comment)](https://github.com/dipeshsukhia/laravel-html-minify/issues/10#issuecomment-1556524103)
> 
> Thanks for the answer, although it doesn't really answer the question. Are you explicitly asking for paid development to port to Laravel 10 ? If so, at what price ?

For maintenance of Package I need sponsors https://github.com/sponsors/dipeshsukhia

**Comment by vmrfriz** [comment]
I have great difficulties in paying from Russia because of the sanctions. Sometime in the summer, I'll try to update this package for Laravel 10 and make a pull-request. If the issue is not resolved before that time.

**Comment by dipeshsukhia** [comment]
Laravel 10 Support added.
