### ISSUE TITLE
Error page is empty

### ISSUE THREAD

**Issue by fammifarendra** [dipeshsukhia/laravel-html-minify#11]
I have set in .env HTML_MINIFY = true,
but when my controller had error, the error page shows nothing, just empty black page

And if I set HTML_MINIFY = false, the error page is normal, shows everything about error

How can i exclude error page ?

**Comment by Jandelson** [comment]
Hi @fammifarendra 
Can you use the file htmlminify in config folder
There a key exclude_route

**Comment by Jandelson** [comment]
@fammifarendra 
I made a new validation about your question.
I see an problem too.
Made a pull resquest to solve the issue.

Can you see my ideia about like solved this issue in Pull requests in this repository.

See you soon!

**Comment by dipeshsukhia** [comment]
Issue resolved in latest release
