### ISSUE TITLE
Question; can we also exclude?

### ISSUE THREAD

**Issue by talistech** [dipeshsukhia/laravel-html-minify#14]
Is there also a trick to exclude certain parts? Just like this, but the other way around:
https://github.com/dipeshsukhia/laravel-html-minify/issues/7#issuecomment-1225968491

For example:
`LaravelHtmlMinifyFacade::htmlMinifyExclude(@include('DoNotMinifyThisFile.css'));`

Thanks

**Comment by dipeshsukhia** [comment]
### exclude minify particular html part
``` php
LaravelHtmlMinifyFacade::excludeHtmlMinify("<div>...</div>");
```
### exclude html minify in blade directory
``` php
@excludeMinify
    <div> exclude code from Minify </div>
@endExcludeMinify
```
