### ISSUE TITLE
Particular Html

### ISSUE THREAD

**Issue by Tjinatsu** [dipeshsukhia/laravel-html-minify#7]
Hello, can you teach me how to use "for particular html part", where should I put it? thanks.

**Comment by dipeshsukhia** [comment]
you can use it for particular Html part 

`LaravelHtmlMinifyFacade::htmlMinify("<div> Here is your HTML </div>");`

you can also use include any blade file also within it 

`LaravelHtmlMinifyFacade::htmlMinify(@include('file'));`
